// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9SJ5mONEvTyNoJE0r0a5jhYpsii6WVFk',
    appId: '1:884752435887:web:b4b282e00a7aa9e652e25a',
    messagingSenderId: '884752435887',
    projectId: 'impact-graphics-za-266ef',
    authDomain: 'impact-graphics-za-266ef.firebaseapp.com',
    storageBucket: 'impact-graphics-za-266ef.firebasestorage.app',
    measurementId: 'G-TNXEBV03ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF3rsbeRfpBTNF6SF4MFoTlaE5tuR6Z_A',
    appId: '1:884752435887:android:ef2d3f143a91a71752e25a',
    messagingSenderId: '884752435887',
    projectId: 'impact-graphics-za-266ef',
    storageBucket: 'impact-graphics-za-266ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwrU89yBKRYTcndvcHBpe3Ow45LXCLcUQ',
    appId: '1:884752435887:ios:3b0d97018389b33152e25a',
    messagingSenderId: '884752435887',
    projectId: 'impact-graphics-za-266ef',
    storageBucket: 'impact-graphics-za-266ef.firebasestorage.app',
    androidClientId: '884752435887-4rf9jhikf4ht028d0gbikmvfgl2o13hr.apps.googleusercontent.com',
    iosClientId: '884752435887-et497k30lajc3he52n5eu72g2dt9dnhs.apps.googleusercontent.com',
    iosBundleId: 'com.impactgraphics.za.impactGraphicsZa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwrU89yBKRYTcndvcHBpe3Ow45LXCLcUQ',
    appId: '1:884752435887:ios:3b0d97018389b33152e25a',
    messagingSenderId: '884752435887',
    projectId: 'impact-graphics-za-266ef',
    storageBucket: 'impact-graphics-za-266ef.firebasestorage.app',
    androidClientId: '884752435887-4rf9jhikf4ht028d0gbikmvfgl2o13hr.apps.googleusercontent.com',
    iosClientId: '884752435887-et497k30lajc3he52n5eu72g2dt9dnhs.apps.googleusercontent.com',
    iosBundleId: 'com.impactgraphics.za.impactGraphicsZa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9SJ5mONEvTyNoJE0r0a5jhYpsii6WVFk',
    appId: '1:884752435887:web:fefc4e5cff34c32952e25a',
    messagingSenderId: '884752435887',
    projectId: 'impact-graphics-za-266ef',
    authDomain: 'impact-graphics-za-266ef.firebaseapp.com',
    storageBucket: 'impact-graphics-za-266ef.firebasestorage.app',
    measurementId: 'G-WTPMWRG1F6',
  );

}